export const CLEAR_GROUPS_RESPONSE = "CLEAR_GROUPS_RESPONSE";
export const CLEAR_GROUPS_ERROR = "CLEAR_GROUPS_ERROR";

export const GET_GROUPS_REQUEST = "GET_GROUPS_REQUEST";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAILURE = "GET_GROUPS_FAILURE";

export const GET_GROUPS_DETAIL_REQUEST = "GET_GROUPS_DETAIL_REQUEST";
export const GET_GROUPS_DETAIL_SUCCESS = "GET_GROUPS_DETAIL_SUCCESS";
export const GET_GROUPS_DETAIL_FAILURE = "GET_GROUPS_DETAIL_FAILURE";

export const POST_CREATE_GROUP_REQUEST = "POST_CREATE_GROUP_REQUEST";
export const POST_CREATE_GROUP_SUCCESS = "POST_CREATE_GROUP_SUCCESS";
export const POST_CREATE_GROUP_FAILURE = "POST_CREATE_GROUP_FAILURE";

export const POST_JOIN_GROUP_REQUEST = "POST_JOIN_GROUP_REQUEST";
export const POST_JOIN_GROUP_SUCCESS = "POST_JOIN_GROUP_SUCCESS";
export const POST_JOIN_GROUP_FAILURE = "POST_JOIN_GROUP_FAILURE";

export const POST_ADD_USERS_REQUEST = "POST_ADD_USERS_REQUEST";
export const POST_ADD_USERS_SUCCESS = "POST_ADD_USERS_SUCCESS";
export const POST_ADD_USERS_FAILURE = "POST_ADD_USERS_FAILURE";

export const PATCH_NAME_REQUEST = "PATCH_NAME_REQUEST";
export const PATCH_NAME_SUCCESS = "PATCH_NAME_SUCCESS";
export const PATCH_NAME_FAILURE = "PATCH_NAME_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
