export const CLEAR_PAYMENTS_RESPONSE = "CLEAR_PAYMENTS_RESPONSE";
export const CLEAR_PAYMENTS_ERROR = "CLEAR_PAYMENTS_ERROR";

export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";

export const POST_CAPTURE_REQUEST = "POST_CAPTURE_REQUEST";
export const POST_CAPTURE_SUCCESS = "POST_CAPTURE_SUCCESS";
export const POST_CAPTURE_FAILURE = "POST_CAPTURE_FAILURE";
