export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE = "POST_LOGIN_FAILURE";

export const DELETE_LOGOUT_REQUEST = "DELETE_LOGOUT_REQUEST";
export const DELETE_LOGOUT_SUCCESS = "DELETE_LOGOUT_SUCCESS";
export const DELETE_LOGOUT_FAILURE = "DELETE_LOGOUT_FAILURE";

export const DELETE_LOGOUT_ALL_REQUEST = "DELETE_LOGOUT_ALL_REQUEST";
export const DELETE_LOGOUT_ALL_SUCCESS = "DELETE_LOGOUT_ALL_SUCCESS";
export const DELETE_LOGOUT_ALL_FAILURE = "DELETE_LOGOUT_ALL_FAILURE";
