export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILURE = "POST_REGISTER_FAILURE";

export const POST_VERIFY_EMAIL_REQUEST = "POST_VERIFY_EMAIL_REQUEST";
export const POST_VERIFY_EMAIL_SUCCESS = "POST_VERIFY_EMAIL_SUCCESS";
export const POST_VERIFY_EMAIL_FAILURE = "POST_VERIFY_EMAIL_FAILURE";

export const POST_RESEND_VERIFICATION_CODE_REQUEST =
  "POST_RESEND_VERIFICATION_CODE_REQUEST";
export const POST_RESEND_VERIFICATION_CODE_SUCCESS =
  "POST_RESEND_VERIFICATION_CODE_SUCCESS";
export const POST_RESEND_VERIFICATION_CODE_FAILURE =
  "POST_RESEND_VERIFICATION_CODE_FAILURE";
