export const CLEAR_USERS_RESPONSE = "CLEAR_USERS_RESPONSE";
export const CLEAR_USERS_ERROR = "CLEAR_USERS_ERROR";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILURE = "POST_REGISTER_FAILURE";

export const POST_VERIFY_EMAIL_REQUEST = "POST_VERIFY_EMAIL_REQUEST";
export const POST_VERIFY_EMAIL_SUCCESS = "POST_VERIFY_EMAIL_SUCCESS";
export const POST_VERIFY_EMAIL_FAILURE = "POST_VERIFY_EMAIL_FAILURE";

export const POST_RESEND_VERIFICATION_CODE_REQUEST =
  "POST_RESEND_VERIFICATION_CODE_REQUEST";
export const POST_RESEND_VERIFICATION_CODE_SUCCESS =
  "POST_RESEND_VERIFICATION_CODE_SUCCESS";
export const POST_RESEND_VERIFICATION_CODE_FAILURE =
  "POST_RESEND_VERIFICATION_CODE_FAILURE";

export const POST_FORGOT_PASSWORD_REQUEST = "POST_FORGOT_PASSWORD_REQUEST";
export const POST_FORGOT_PASSWORD_SUCCESS = "POST_FORGOT_PASSWORD_SUCCESS";
export const POST_FORGOT_PASSWORD_FAILURE = "POST_FORGOT_PASSWORD_FAILURE";

export const POST_RESET_PASSWORD_REQUEST = "POST_RESET_PASSWORD_REQUEST";
export const POST_RESET_PASSWORD_SUCCESS = "POST_RESET_PASSWORD_SUCCESS";
export const POST_RESET_PASSWORD_FAILURE = "POST_RESET_PASSWORD_FAILURE";

export const PATCH_UPDATE_PROFILE_REQUEST = "PATCH_UPDATE_PROFILE_REQUEST";
export const PATCH_UPDATE_PROFILE_SUCCESS = "PATCH_UPDATE_PROFILE_SUCCESS";
export const PATCH_UPDATE_PROFILE_FAILURE = "PATCH_UPDATE_PROFILE_FAILURE";
