export const CLEAR_EXPENSES_RESPONSE = "CLEAR_EXPENSES_RESPONSE";
export const CLEAR_EXPENSES_ERROR = "CLEAR_EXPENSES_ERROR";

export const GET_USER_DEBTS_REQUEST = "GET_USER_DEBTS_REQUEST";
export const GET_USER_DEBTS_SUCCESS = "GET_USER_DEBTS_SUCCESS";
export const GET_USER_DEBTS_FAILURE = "GET_USER_DEBTS_FAILURE";

export const POST_CREATE_EXPENSE_REQUEST = "POST_CREATE_EXPENSE_REQUEST";
export const POST_CREATE_EXPENSE_SUCCESS = "POST_CREATE_EXPENSE_SUCCESS";
export const POST_CREATE_EXPENSE_FAILURE = "POST_CREATE_EXPENSE_FAILURE";

export const POST_PAY_IN_CASH_REQUEST = "POST_PAY_IN_CASH_REQUEST";
export const POST_PAY_IN_CASH_SUCCESS = "POST_PAY_IN_CASH_SUCCESS";
export const POST_PAY_IN_CASH_FAILURE = "POST_PAY_IN_CASH_FAILURE";
